document.writeln("<html lang=\'en\'>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title>Document</title>");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width,initial-scale=1\'>");
document.writeln("		<link rel=\'stylesheet\' href=\'css/bootstrap.css\'>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' href=\'css/footer.css\'/>");
document.writeln("		<script src=\'js/jquery.min.js\'></script>");
document.writeln("		<script src=\'js/popper.min.js\'></script>");
document.writeln("		<script src=\'js/bootstrap.min.js\'></script>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div class=\'d1 my-5\'>");
document.writeln("		    <!-- 第一个 -->");
document.writeln("				<div class=\'d-flex justify-content-around mb-5\'>");
document.writeln("					<div class=\'mt-5\'>");
document.writeln("						<h5 class=\'\'>About Change</h5>");
document.writeln("						<div class=\'text-muted small mt-4\'>");
document.writeln("						  <p>本店商品均为易碎品，非质量问题</p>");
document.writeln("						  <p>谢绝退换，如有质量问题，本店承</p>");
document.writeln("						  <p>担运费调换</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'mt-5\'>");
document.writeln("						<h5>Service</h5>");
document.writeln("						<div class=\'text-muted small mt-4\'>");
document.writeln("						  <p>消費者保障服务</p>");
document.writeln("              <p>七天无理由退款</p>");
document.writeln("              <p> 假一赔三</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'mt-5\'>");
document.writeln("						<h5>About Color</h5>");
document.writeln("						<div class=\'text-muted small mt-4\'>");
document.writeln("						  <p>本店商品均为易碎品，非质量问题</p>");
document.writeln("						  <p>谢绝退换，如有质量问题，本店承</p>");
document.writeln("						  <p>担运费调换</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'mt-5\'>");
document.writeln("						<img src=\'img/logo%20(2).webp\' >");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<!-- 第二个 -->");
document.writeln("				<div class=\'d-flex justify-content-around border-bottom pb-5\'>");
document.writeln("					<div>");
document.writeln("					  <h5 class=\'mb-4\'>Online Payment</h5>");
document.writeln("						<div >");
document.writeln("							<img class=\'ig\' src=\'img/a.png\' >");
document.writeln("							<img class=\'ig\' src=\'img/b.png\' >");
document.writeln("							<img class=\'ig\' src=\'img/c.png\' >");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'pl-5\'>");
document.writeln("						<h5>Online Payment</h5>");
document.writeln("						<div  class=\'text-muted small mt-4\'>");
document.writeln("						  <p>非质量问题谢绝退换，如有质量问</p>");
document.writeln("						  <p>题，本店承担运费调换</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div>");
document.writeln("						<h5>Wechat</h5>");
document.writeln("						<div  class=\'text-muted small mt-4\'>");
document.writeln("						  <p>非质量问题谢绝退换，如有质量问</p>");
document.writeln("						  <p>题，本店承担运费调换</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div>");
document.writeln("						<h5>Social App</h5>");
document.writeln("						<img src=\'./img/wechat.png\' >");
document.writeln("						<img src=\'img/sinablog.png\' >");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<!-- 第三个 -->");
document.writeln("				<div class=\'d-flex justify-content-around border-bottom mt-5\'>");
document.writeln("					<div>");
document.writeln("						<h5>关于产品</h5>");
document.writeln("						<div class=\'text-muted small\'>");
document.writeln("						  <p>about color</p>");
document.writeln("						  <p>所有商品均为实物拍摄，各浏览器</p>");
document.writeln("						  <p>显示有所不同，对此要求高的买家</p>");
document.writeln("						  <p>慎拍</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div>");
document.writeln("						<h5>关于退货</h5>");
document.writeln("						<div class=\'text-muted small\'>");
document.writeln("						  <p>about change</p>");
document.writeln("						  <p>本店商品均为易碎品，非质量问题</p>");
document.writeln("						  <p>谢绝退换，如有质量问题，本店承</p>");
document.writeln("						  <p>担运费调换</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div>");
document.writeln("						<h5>关于产品</h5>");
document.writeln("						");
document.writeln("						<div class=\'text-muted small\'>");
document.writeln("						  <p>about change</p>");
document.writeln("						  <p>本店商品均为易碎品，非质量问题</p>");
document.writeln("						  <p>谢绝退换，如有质量问题，本店承</p>");
document.writeln("						  <p>担运费调换</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div>");
document.writeln("						<h5>扫码关注</h5>");
document.writeln("						<p class=\'text-muted small\'>about change</p>");
document.writeln("						<img src=\'img/d.webp\' >");
document.writeln("						<p class=\'text-muted small\'>搜索微信号：HUAYU</p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			  <!-- 第四个 -->");
document.writeln("				<div class=\'text-center text-muted small p-2 mt-2\'>");
document.writeln("					<p>Copyright © 2010-2015花语文化传播有限公司 All rights reserved</p>");
document.writeln("				</div>");
document.writeln("		</div>");
document.writeln("	</body>");
document.writeln("</html>");