document.writeln("<html lang=\'en\'>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title>Document</title>");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width,initial-scale=1\'>");
document.writeln("		<link rel=\'stylesheet\' href=\'css/bootstrap.css\'>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' href=\'css/header.css\'/>");
document.writeln("		<script src=\'js/jquery.min.js\'></script>");
document.writeln("		<script src=\'js/popper.min.js\'></script>");
document.writeln("		<script src=\'js/bootstrap.min.js\'></script>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div class=\'row no-gutters\'>");
document.writeln("			<div class=\'col-lg-12 d-sm-none d-lg-block my_bgc\'>");
document.writeln("				<div class=\'d-flex justify-content-around\'>");
document.writeln("					<div class=\'navbar navbar-expand-lg text-muted small\'>");
document.writeln("						<ul class=\'navbar-nav\'>");
document.writeln("							<li class=\'nav-item\'>");
document.writeln("								<span class=\'nav-link\'>在线时间 08:30~21:30</span>");
document.writeln("							</li>");
document.writeln("							<li class=\'nav-item\'>");
document.writeln("								<span class=\'nav-link\'>欢迎访问花语在线商城！</span>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'navbar navbar-expand-lg\'>");
document.writeln("						<ul class=\'navbar-nav\'>");
document.writeln("							<li class=\'nav-item\'>");
document.writeln("								<a href=\'\' class=\'nav-link\'>");
document.writeln("									<img src=\'img/care1.png\' >");
document.writeln("								</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'nav-item\'>");
document.writeln("								<a href=\'\' class=\'nav-link\'>");
document.writeln("									<img src=\'img/order1.png\' >");
document.writeln("								</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'nav-item\'>");
document.writeln("								<a href=\'\' class=\'nav-link\'>");
document.writeln("									<img src=\'img/shop_car1.png\' >");
document.writeln("								</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div class=\'col-lg-12 my_bgimg\'>");
document.writeln("				<div class=\'text-center d-sm-none d-lg-block\'>");
document.writeln("					<img src=\'img/logo.webp\' alt=\'\' class=\'w_6 mt-3\'>");
document.writeln("				</div>");
document.writeln("			<div class=\' small mt-3\'>");
document.writeln("				<ul class=\'nav justify-content-center\'>");
document.writeln("					<li class=\'nav-item mx-3\'>");
document.writeln("						<a href=\'index.html\' class=\'nav-link text-muted\'>商品首页</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'nav-item mx-3\'>");
document.writeln("						<a href=\'shangp.html\' class=\'nav-link text-muted\'>所有商品</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'nav-item mx-3\'>");
document.writeln("						<a href=\'pay.html\' class=\'nav-link text-muted\'>支付方式</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'nav-item mx-3\'>");
document.writeln("						<a href=\'huayu.html\' class=\'nav-link text-muted\'>关于花语</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'nav-item mx-3\'>");
document.writeln("						<a href=\'xianxia.html\' class=\'nav-link text-muted\'>线下门店</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("				");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</body>");
document.writeln("</html>");